name: tmda
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  dio: ^5.1.2
  flutter_animate: ^4.1.1+1
  hive_flutter: ^1.1.0
  get_it: ^7.6.0
  dartz: ^0.10.1
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  url_launcher: ^6.1.11
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_screenutil: ^5.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_logo.png
    - assets/images/test_image.jpg
    - assets/images/neon_background.png
    - assets/images/tv_test_image.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-thin.ttf
          weight: 100
        - asset: assets/font/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins-Black.ttf
          weight: 900
